# Generated by Django 5.2.1 on 2025-09-20 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_item_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Material',
            new_name='Category',
        ),
    ]
