# Generated by Django 5.2.1 on 2025-09-20 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_rename_material_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='material',
            new_name='category',
        ),
    ]
