# Generated by Django 5.2.1 on 2025-10-12 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_category_name_en_category_name_it'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='thickness',
            new_name='depth',
        ),
    ]
