# Generated by Django 5.2.1 on 2025-11-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_rename_thickness_item_depth'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
