# Generated by Django 5.2.1 on 2025-06-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_examplemodel_description_en_gb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplemodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examplemodel',
            name='description_en_gb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examplemodel',
            name='description_it_it',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examplemodel',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='examplemodel',
            name='name_en_gb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='examplemodel',
            name='name_it_it',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
