# Generated by Django 5.2.1 on 2025-06-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplemodel',
            name='description_en_gb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='examplemodel',
            name='description_it_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='examplemodel',
            name='name_en_gb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='examplemodel',
            name='name_it_it',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
