# Generated by Django 5.2.1 on 2025-09-20 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_examplemodel_created_at_examplemodel_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examplemodel',
            old_name='description_en_gb',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='examplemodel',
            old_name='description_it_it',
            new_name='description_it',
        ),
        migrations.RenameField(
            model_name='examplemodel',
            old_name='name_en_gb',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='examplemodel',
            old_name='name_it_it',
            new_name='name_it',
        ),
    ]
